version: "3.8"

services:
  fhevm-node:
    image: ghcr.io/zama-ai/ethermint-dev-node:v0.4.2
    container_name: fhevm-node
    restart: unless-stopped
    ports:
      - "8545:8545"
      - "8546:8546"
      - "26657:26657"
    stdin_open: true
    tty: true
